// <auto-generated />
using System;
using CmsDbEFCodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CmsDbEFCodeFirst.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20201111075334_ChangedStringLength Kontonummer")]
    partial class ChangedStringLengthKontonummer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CmsDbEFCodeFirst.Models.Konto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Kontonummer")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Konton");
                });

            modelBuilder.Entity("CmsDbEFCodeFirst.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AntalBilar")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personer");
                });

            modelBuilder.Entity("CmsDbEFCodeFirst.Models.Konto", b =>
                {
                    b.HasOne("CmsDbEFCodeFirst.Models.Person", null)
                        .WithMany("Konton")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("CmsDbEFCodeFirst.Models.Person", b =>
                {
                    b.Navigation("Konton");
                });
#pragma warning restore 612, 618
        }
    }
}
